### ISSUE TITLE
Get all 2i2c engineers access to UToronto Azure portal

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#386] opened 2022-03-10 19:48 UTC
### Background and proposal

Currently, only me and @GeorgianaElena have UToronto accounts, and hence access to the Azure subscription. This restricts debugging and fixing by other 2i2c engineers, since they only have partial (k8s) access to the cluster. While long term getting each engineer an individual account at multiple universities is untenable, I think for *right now* we should just bite the bullet specifically for UToronto and get accounts.

## Implementation

I think we'll need to co-ordinate with UToronto folks to do the paperwork needed to get a UToronto account, and get it added to the Azure admin portal. The effort was more minimal than what was required for Columbia accounts.

- [x] @yuvipanda
- [x] @GeorgianaElena 
- [x] @sgibson91 
- [x] @damianavila 
- [x] @jmunroe
~@choldgraf~
~(optional) @consideRatio (update: opts out of working to set this up)~

**Comment by yuvipanda** [comment] 2022-03-10 19:51
This would've been a big problem for https://github.com/2i2c-org/infrastructure/issues/1081, as the fix required direct access to the Azure subscription.

**Comment by choldgraf** [comment] 2022-03-10 21:21
After https://github.com/2i2c-org/infrastructure/issues/1081, I think we should definitely double-down to resolve this issue. That said, I think that creating a UToronto account for each engineer is not sustainable with our current practices. Is there any way for us to have more control over access to this deployment?

Ultimately, it feels like this situation where we need to create institutional accounts for each 2i2c engineer needs to be a very extreme and uncommon situation, probably one that carries a very high price tag because of the penalty that we pay in coordinating accounts, giving access, etc.

In this situation, are there any other creative ways that we could have set up the cloud infrastructure to avoid the need for Toronto-specific Azure accounts for each person?

**Comment by yuvipanda** [comment] 2022-03-10 21:28
@choldgraf while I agree that this is not a long term sustainable situation, I want us to get out of our current short term unsustainable situation first. I would really like for us to get at least all other current members access, and figure out alternatives in parallel. I don't want the perfect to be the enemy of the good. We have been looking for alternatives for a while and have not found time to do the work of exploring them yet, and I don't think that will change in the near future. So specific to just Toronto, let's just do this so me and @GeorgianaElena can stop being single points of failure...

**Comment by choldgraf** [comment] 2022-03-10 21:36
OK - then I think we need to:

1. Define the process by which people can get access. Who do team members need to email? What information do they need to provide?
2. Define some documentation that is specific to the U. Toronto hub so that team members know how to access this cloud infrastructure specifically (maybe that's a part of https://github.com/2i2c-org/infrastructure/pull/714)

Have we got `1` documented somewhere?

**Comment by yuvipanda** [comment] 2022-03-10 21:37
@choldgraf I was just chatting with @colliand and he has offered to help with 1. 

I don't think (2) is anything specific outside of what is needed to access Azure infrastructure (do we have docs for that?) - just different login.

**Comment by choldgraf** [comment] 2022-03-10 21:38
ok sounds good. re: 2, yeah I agree that it shouldn't be much different, but "remember to use a different log-in for this specific community" is still a pretty important one to remember haha

**Comment by yuvipanda** [comment] 2022-03-15 00:50
I've just sent an email to Jeremy et al, asking two separate questions:

1. Can we get our engineers access to the Azure portal without a utoronto.ca account?
2. What is the process for getting them a utoronto.ca account, so they can test hub login?

**Comment by consideRatio** [comment] 2022-03-16 16:04
### Sprint team meeting notes

We are waiting for our contact to proceed.

We hope to use the 2i2c accounts to access Azure. If not, we have to ask how we can get their accounts.

**Comment by yuvipanda** [comment] 2022-03-30 15:47
Update: Jeremy said he'd email everyone on the list with new credentials for access to the Azure portal! They'd need date of birth to setup utoronto.ca ID (utorid), I'll co-ordinate finding a way to get that info.

**Comment by sgibson91** [comment] 2022-06-30 11:26
I activated my UTOR ID yesterday

**Comment by damianavila** [comment] 2022-07-11 20:39
I activated my UTOR ID as well.

@choldgraf and @consideRatio, you are both listed at the top message, can you confirm if you are going to activate the UTOR ID? Thanks!

**Comment by consideRatio** [comment] 2022-07-11 21:18
@damianavila I've not seen any invite or similar and is not taking action towards getting a UTOR ID! I updated the original post.

**Comment by choldgraf** [comment] 2022-07-12 10:31
@damianavila I don't think that we should block this on me getting access, I cannot think of a situation where I *should* have access to this cluster, given that I would have no idea how to do anything with it if I did :-)

Can you / others think of a reason why me (or, e.g., folks on @2i2c-org/partnerships-and-community-guidance ) would need access? If not, I think we should restrict this to our engineering team.

**Comment by jmunroe** [comment] 2022-07-12 11:39
While it's true that @2i2c-org/partnerships-and-community-guidance won't need access to the Azure subscription, that hub uses AzureAD and requires a UTOR ID to be able to log on to it.  Assuming that we should be able see what the UToronto community sees, I think I will need to be able to log into that JupyterHub.

Is there a way to set up oauth_login so that there is an alternate (but maybe not publiclized) way of authenticating to the hub that doesn't depend on AzureAD?

**Comment by damianavila** [comment] 2022-07-12 21:30
@jmunroe has a good point on the usage. Additionally, since we are all rotating in support, we all "technically" need access to that hub (still, I understand if people want to opt-out of the process).

**Comment by jmunroe** [comment] 2022-09-14 15:55
I've added myself to the list of people needing access to AzureAD to be able to log-in to the UToronto hub.

**Comment by sgibson91** [comment] 2022-10-05 14:03
Seems like everyone is checked off in the top comment - time to close?

**Comment by jmunroe** [comment] 2022-10-05 14:40
Yes. Just confirmed my UTORid.  I think we can close this issue.

**Closed** 2022-10-05 14:47 UTC
