### ISSUE TITLE
Get all 2i2c engineers access to UToronto Azure portal

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#385] opened 2022-03-10 19:48 UTC
### Background and proposal

Currently, only me and @GeorgianaElena have UToronto accounts, and hence access to the Azure subscription. This restricts debugging and fixing by other 2i2c engineers, since they only have partial (k8s) access to the cluster. While long term getting each engineer an individual account at multiple universities is untenable, I think for *right now* we should just bite the bullet specifically for UToronto and get accounts.

### Implementation guide and constraints

Accounts exist for

**Comment by consideRatio** [comment] 2022-03-10 20:24
Closed as a unfinished duplicate of #386 probably created by mistake.

**Closed by consideRatio** 2022-03-10 20:24 UTC

**Comment by yuvipanda** [comment] 2022-03-10 20:29
Ah, no idea how this happened. Thansk for the catch @consideRatio
